baseurl = "/"
title = "Down For Maintenance"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = ""

[params]
  Keywords = ""
  Description = "We'll be back shortly!"
  Avatar = "img/logo.png"
  SelfIntro = "Down for Maintenance"
  Email = "joe@depumpo.com"
